### ISSUE TITLE
wish: better diagnostics for "KeyError: 'TODO_DIR'"

### ISSUE THREAD

**Issue by markstos** [mivok/todotxt-tmsa#2]
I ran `t verify`, but it crashed and it's not clear what's wrong. A better diagnostic would be helpful:

```
$ t verify
Traceback (most recent call last):
  File "/home/mark/.todo.actions.d/verify", line 143, in <module>
    unmanaged = find_unmanaged()
  File "/home/mark/.todo.actions.d/verify", line 68, in find_unmanaged
    os.chdir(os.environ["TODO_DIR"])
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'TODO_DIR'
```

I presume there was a problem reading TODO_DIR from the environment, so I'll investigate that.

**Comment by markstos** [comment]
Here's some example Python code that could be used to provide a better diagnostic. It seems to confirm that setting TODO_DIR in the environment might fix the issue. 

https://github.com/mstave/tdg/blob/f745cac5c144773f7e3a1e0e925c4f6a4b6c5b34/tdi.py#L112

I'm not sure why `todo.sh` isn't taking care of this for me when it loads plugins.

**Comment by markstos** [comment]
Turns out I had a very old `.todo/config` file that merely defined `TODO_DIR`, but did not _export_ it. exporting TODO_DIR there resolved the issue for me.

**Comment by markstos** [comment]
Closing this, as I don't currently use this tool, and no one else has voted or commented on the issue in 5 years.
